import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { LibraryAdd } from "@styled-icons/material/LibraryAdd";
import { OndemandVideo } from "@styled-icons/material/OndemandVideo";

const inter = Inter({ subsets: ["latin"] });

import {
  // alignment
  createAlignPlugin,
  ELEMENT_H1,
  ELEMENT_H2,
  ELEMENT_H3,
  ELEMENT_H4,
  ELEMENT_H5,
  ELEMENT_H6,
  ELEMENT_PARAGRAPH,
  Plate,
  PlateProvider,
  // image
  createImagePlugin,
  createMediaEmbedPlugin,
  createSelectOnBackspacePlugin,
  ELEMENT_IMAGE,
  ELEMENT_MEDIA_EMBED,
  ImageToolbarButton,
  MediaEmbedToolbarButton,
} from "@udecode/plate";
import { Toolbar } from "@/Components/Toolbar/toolbar";
import { AlignToolbarButtons } from "@/Components/align/AlignToolbarButtons";
import { plateUI } from "@/Components/common/plateUI";
import { createMyPlugins } from "@/Components/common/createmyplugin";
import { basicNodesPlugins } from "@/Components/basic-nodes/basicNodesPlugins";
import SaveButton from "@/Components/savebutton/savebutton";
import mydata from "./test.json";

export default function Home() {
  const editableProps = {
    spellCheck: false,
    autoFocus: false,
    placeholder: "Type…",
  };

  const plugins = createMyPlugins(
    [
      ...basicNodesPlugins,

      createAlignPlugin({
        inject: {
          props: {
            validTypes: [
              ELEMENT_PARAGRAPH,
              ELEMENT_H1,
              ELEMENT_H2,
              ELEMENT_H3,
              ELEMENT_H4,
              ELEMENT_H5,
              ELEMENT_H6,
            ],
          },
        },
      }),
      createImagePlugin(),
      createMediaEmbedPlugin(),
      createSelectOnBackspacePlugin({
        options: {
          query: {
            allow: [ELEMENT_IMAGE, ELEMENT_MEDIA_EMBED],
          },
        },
      }),
    ],
    {
      components: plateUI,
    }
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <PlateProvider plugins={plugins} initialValue={mydata}>
          <Toolbar>
            <AlignToolbarButtons />
            <ImageToolbarButton icon={<LibraryAdd />} />
            <MediaEmbedToolbarButton icon={<OndemandVideo />} />
            <SaveButton />
          </Toolbar>
          <Plate editableProps={editableProps} />
        </PlateProvider>
      </main>
    </>
  );
}
